#* para base de datos de oracle

version: '3.8'
services:
#   oracle-db:
#     image: container-registry.oracle.com/database/express:latest
#     ports:
#       - "1521:1521"
#       - "5500:5500"
#     environment:
#       - ORACLE_PWD=Admin12345
#       - ORACLE_CHARACTERSET=AL32UTF8
#     volumes:
#       - ./oracle-data:/opt/oracle/oradata
#     container_name: oracle-db

#* para base de datos de postgres

  postgres-db-colegio:
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
